### ISSUE TITLE
Create benchmarking script for telemetry service

### ISSUE THREAD

**Issue by chinmoy12c** [BharatSahAIyak/telemetry#17]

**Comment by PriyanshiATSamagra** [comment]
- [ ] API Testing
- [ ] Load Testing

**Comment by dhruv-1001** [comment]
@PriyanshiATSamagra to add Screenshot for telemetry benchmark result.

**Comment by PriyanshiATSamagra** [comment]
Added screenshot or result.

- [ ] Benchmarking-Load-Testing core refactoring for supporting other service load testing as well.
